language: go

sudo: required
dist: bionic

go_import_path: cryptsetup

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcryptsetup12 libcryptsetup-dev

script:
  - sudo -E env "PATH=$PATH" go test -v ./...
